### ISSUE TITLE
Menu links strong.forward missing

### ISSUE THREAD

**Issue by b-fender** [ErdmannFreunde/euf_nutshell#10]
Hallo Dennis, neulich ist mir aufgefallen, das in scss/components/navs.scss noch nicht die CSS-Klasse strong.forward berücksichtigt ist, die von Contao vergeben wird, wenn eine Seite den Seitentyp "Weiterleitung" hat und im Menu erscheint.

Das betrifft .nav--horizontal, nav--vertical, nav--border.

Hier müsste noch jeweils strong.forward ergänzt werden.

also vorher z.B. (scss/components/navs.scss, Z. 28 ff)

```scss
.nav--horizontal {
  ul {
    display: flex;
    flex-direction: column;
    
    @include media-query(screen-menu) {
      flex-direction: row;
    }
  }
  a,
  strong.active,
  strong.trail {
    display: block;
    padding: calc(var(--nav--main__item-padding) / 2) var(--nav--main__item-padding);
  }
}

```

Korrektur:

```scss
.nav--horizontal {
  ul {
    display: flex;
    flex-direction: column;
    
    @include media-query(screen-menu) {
      flex-direction: row;
    }
  }
  
  a,
  strong.active,
  strong.trail,
  strong.forward  {
    display: block;
    padding: calc(var(--nav--main__item-padding) / 2) var(--nav--main__item-padding);
  }
}

```

Dies gilt, wie gesagt auch für nav--horizontal und nav--border.

beste Grüße, Jochen
