### ISSUE TITLE
.nav--horizontal cannot be centered

### ISSUE THREAD

**Issue by richardhj** [ErdmannFreunde/euf_nutshell#3]
The list items within a `.nav--horizontal` get floated. You cannot center the whole navigation, I used to the following to do that:
```css
ul {
text-align: center
}
li {
display: inline-block
}
```
So rather use `display: inline-block`?
